package de.tu_darmstadt.epool.pfoertner.common.architecture.model;

public interface Member {
    /**
     * Members have a unique int identifier
     */
    int getId();

    /**
     * Foreign key, referring to the office that the member is a part of
     */
    int getOfficeId();

    /**
     * First name of the member
     */
    String getFirstName();

    /**
     * Last name of the member
     */
    String getLastName();

    /**
     * Personal status of the member that is being displayed on the door panel (e.g. Do not disturb)
     */
    String getStatus();

    /**
     * URL to download the picture of this office member
     */
    String getPicture();

    /**
     * MD5 code generated by the server when a picture is uploaded. Used to check if the picture changed.
     */
    String getPictureMD5();

    /**
     * Server auth code, uploaded by the admin app and used to retrieve an auth token to access the google calendar
     *
     * https://developers.google.com/calendar/auth
     */
    String getServerAuthCode();

    /**
     * URL of the "office hours" calendar of the office member
     */
    String getCalendarId();

    /**
     * Google email address of the office member
     */
    String getEmail();

    /**
     * Id of the webhook channel for calendar updates
     */
    String getWebhookId();
}
